### ISSUE TITLE
Staffbot crashes when checking warnings

### ISSUE THREAD

**Issue by connermcd** [Trench-Wars/twcore#1]
**Reported by Maverick on 27 Nov 1971 04:46 UTC**
Nethila: "When checking warnings via Staffbot, please keep in mind that staffbot wont take names that has ' or " in them. Those names will kill staffbot just like that. So if you accidently killed it, just spawn it or get a mod to do it for you off RoboQueen."

**Comment by connermcd** [comment]
**Modified by Maverick on 25 Jun 1995 07:26 UTC**

**Comment by connermcd** [comment]
**Modified by Maverick on 27 May 2003 19:53 UTC**

**Comment by connermcd** [comment]
**Comment by dugwyler on 2 Sep 1958 10:27 UTC**
This ''should'' now be fixed.  In the warning-check SQL queries, slashes were not being added.  Will not close this ticket until someone verifies this is now working.

**Comment by connermcd** [comment]
**Comment by Maverick on 24 Dec 1975 03:37 UTC**
Notice that this bot isn't used on Roboking so it won't be automatically tested after a SVN update. 

This bot should be given a temporary name and spawned just to test if this bug has been fixed.

**Comment by connermcd** [comment]
**Comment by dugwyler on 21 Aug 2000 09:12 UTC**
Well, this one definitely sounded like an addSlashesToString problem, and that method was not used on the query ... therefore I think it's a safe bet (95%) that this fixed it.  Reopen if not fixed.

**Comment by connermcd** [comment]
**Comment by Maverick on 17 Feb 1977 16:36 UTC**
No, please don't close it until it's tested that it's fixed. Otherwise it's forgotten.

**Comment by connermcd** [comment]
**Comment by dugwyler on 28 Jul 2031 22:49 UTC**
Well, fair enough -- the others should be reopened then as well.

This one, though, of any of these tickets, I think is the most likely to be fixed... so that it's ironic you chose to reopen it in particular.

How are we testing these?  There was mention of running StaffBot on a different name.  Is there an individual in charge of verifying things work?

**Comment by connermcd** [comment]
**Comment by Maverick on 27 Jun 1967 09:54 UTC**
The one who fixed the problem should also test if it works himself, it's part of fixing the whole problem imo. 

You can test it by putting up your own bot core in TW Dev zone or contact me for testing it in TW (which should only be done if it's absolutely impossible to test it yourself).
If you need a test database with test data, you can contact me for credentials for connecting to a TW database on twcore.org.

**Comment by connermcd** [comment]
**Comment by freakmonger on 7 May 1978 09:26 UTC**
It still crashes for me. 

java.lang.NullPointerException
	at twcore.bots.staffbot.staffbot.queryWarningsFrom(staffbot.java:238)
	at twcore.bots.staffbot.staffbot.handleEvent(staffbot.java:188)
	at twcore.core.net.GamePacketInterpreter.handleChatMessage(GamePacketInterpreter.java:468)
	at twcore.core.net.GamePacketInterpreter.translateNormalPacket(GamePacketInterpreter.java:188)
	at twcore.core.net.GamePacketInterpreter.translateGamePacket(GamePacketInterpreter.java:136)
	at twcore.core.net.ReliablePacketHandler.handleReliableMessage(ReliablePacketHandler.java:88)
	at twcore.core.net.GamePacketInterpreter.translateSpecialPacket(GamePacketInterpreter.java:310)
	at twcore.core.net.GamePacketInterpreter.translateGamePacket(GamePacketInterpreter.java:134)
	at twcore.core.Session.run(Session.java:310)

**Comment by connermcd** [comment]
**Comment by Maverick on 25 Oct 1941 18:10 UTC**
freakmonger, you did use the latest version from the repository?

**Comment by connermcd** [comment]
**Comment by Maverick on 21 Jul 2019 01:33 UTC**
Staffbot still crashes when you do !warnings bla"bla .

**Comment by connermcd** [comment]
**Comment by Maverick on 3 Jul 2011 04:13 UTC**
This ticket has been summarized in ticket:108.
