### ISSUE TITLE
EventBot

### ISSUE THREAD

**Issue by connermcd** [Trench-Wars/twcore#22]
**Reported by Maverick on 3 Feb 1974 04:32 UTC**
Automate the way that players can request events and usable for ERs to see which event is requested the most (etc).

**Comment by connermcd** [comment]
**Modified by Maverick on 25 Mar 1950 12:24 UTC**

**Comment by connermcd** [comment]
**Comment by flibb on 3 May 1968 20:08 UTC**
perhaps this can be incorporated in zonerbot somehow. it already allows zhs to add requests

**Comment by connermcd** [comment]
**Comment by Maverick on 13 Apr 1997 12:16 UTC**
yes, requests for advertisements, not for events.
I think it's best to make a separate bot out of it since its purpose is so different.

**Comment by connermcd** [comment]
**Comment by flibb on 6 Jul 1954 03:51 UTC**
no, zhs can add requests for events, but no one uses it, another bot means more resources for something that doesn't really add much imo

**Comment by connermcd** [comment]
**Modified by flibb on 8 Aug 1956 01:11 UTC**

**Comment by connermcd** [comment]
**Comment by dugwyler on 14 Sep 1927 10:04 UTC**
ZonerBot is pretty much just there for requesting zone messages.  Perhaps adding this feature to something more public-oriented/accessible, such as RoboHelp?  The bot name itself seems friendly to players.

Is Elleya taking this?

**Comment by connermcd** [comment]
**Comment by Maverick on 28 Sep 2011 05:49 UTC**
Nah, having RoboHelp for such functionality would only be obfuscating its original purpose. The same would happen if you apply it to Zonerbot. I'm sure its better for us, the players and also the people who use TWCore in their own zone to keep each bot focussed on its own single task instead of making a bigass bot that does everything.

Elleya should be working on this although I doubt it since I haven't heard from him in a long while. 
I guess I have to go ask each bot developer what he's doing in order to find out.

**Comment by connermcd** [comment]
**Comment by dugwyler on 26 Jun 1961 03:21 UTC**
I'm just thinking what flibb was -- that it would be yet another bot running yet another thread, and generating even more overhead.

I don't know if it would really obfuscate so much as expand RoboHelp's purpose.  After all, RoboHelp records "on it"'s for ?help calls that include requests for events.  It might alleviate that load a bit.  As a liaison between staff and the public, I think it's rather an ideal place for such functionality.

**Comment by connermcd** [comment]
**Comment by Maverick on 9 Feb 2027 23:44 UTC**
This task is free to take

**Comment by connermcd** [comment]
**Comment by Maverick on 18 Jan 1956 19:06 UTC**
Zonerbot is quite big already so I'm going to make it into a seperate bot so there is enough room for further improvement and more advanced functionality.

**Comment by connermcd** [comment]
**Comment by Barton on 31 May 2000 17:18 UTC**
maybe something like zonerbot & ?advert but then for the eventbot

like it reg's all the ?request's

and maybe by !viewrequests to see all the requests 

maybe limit to to 1 each hour for one person.

**Comment by connermcd** [comment]
**Comment by dugwyler on 6 Sep 1924 01:30 UTC**
I think Mav's pretty much implemented it already, fairly close to this.

Though, the piece about the ?command addition might be useful -- not sure if this is already implemented.  A lot of people presently do "?help host eventname", which could be pretty easily picked up and parsed by the bot.  At the very least RoboHelp should refer them to this new bot.

**Comment by connermcd** [comment]
**Comment by Maverick on 1 Aug 1921 10:52 UTC**
Agreed, that's what I was planning - either have it respond to `?help host ...` or let RoboHelp refer to `:EventBot:!request`.

Another `?command` like `?request` seems a bit redundant to me as what I would like to see is to have the players PM EventBot directly with `!request` instead of through a `?command`.

**Comment by connermcd** [comment]
**Comment by Maverick on 15 Jun 2019 10:14 UTC**
First beta test has been committed and tested for a few weeks by mainly the Trench wars Staff.

Following needs to be done to complete it:
 * Allow players to cancel their own request
 * !removeban (instead of !ban toggle)
 * !listban # (default 10)
 * Make sure you can't !ban yourself or staff
 * Configurable chats (chat for requests, chat for wbduel/base requests)
 * Alias for !fillrequest: !fr
 * If an ER does !fillrequest, a "got it" call count (the count between brackets) will be added to his advert record on the staff statistics.

Discussion topic (staff forum): http://forums.trenchwars.org/showthread.php?t=31867

**Comment by connermcd** [comment]
**Comment by Maverick on 9 Aug 2032 10:22 UTC**
more todos:

 * !subscribe all to have the staff member PM'ed when a request comes in
 * !subscribe bwjs or !subscribe to have the staff member PM'ed when a request comes in for base/wbduel/javduel etc

 * save a "got it" count for taking base/wbduel/javduel requests

**Comment by connermcd** [comment]
**Comment by Maverick on 11 Sep 1936 15:44 UTC**
Did some, left over TODOs:
 * If an ER does !fillrequest, a "got it" call count (the count between brackets) will be added to his advert record on the staff statistics.
 * Spread PMs to subscribers on event request
 * save a "got it" count for taking base/wbduel/javduel requests

**Comment by connermcd** [comment]
**Comment by Maverick on 18 May 1938 01:57 UTC**
changeset:2240

**Comment by connermcd** [comment]
**Comment by Maverick on 12 Jul 1951 07:44 UTC**
changeset:2241

**Comment by connermcd** [comment]
**Comment by Left_Eye on 22 Aug 1925 19:37 UTC**
1:MBananas <ER>> !fillrequest ufc
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).

It spams chat for each player that had requested the event everytime a fillrequest is done.

**Comment by connermcd** [comment]
**Comment by Maverick on 12 Nov 1979 13:44 UTC**
Replying to [Left_Eye](comment:20):
> 
``` 
1:MBananas <ER>> !fillrequest ufc
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
1:EventBot> Informed 10 players (and matching requests removed).
```
Yea I found and fixed that bug while doing the latest changes on the bot.

**Comment by connermcd** [comment]
**Comment by Maverick on 27 Aug 1968 18:10 UTC**
I finished the bot, related changesets: [and [2244](2243])

**Comment by connermcd** [comment]
**Comment by Maverick on 7 Feb 1985 08:11 UTC**
TODO: Remove the message limit (bot ignores people which isn't good)

**Comment by connermcd** [comment]
**Comment by Maverick on 10 Aug 2023 23:04 UTC**
TODO bugfix:
```
[04 06:39](Feb) Krazie_ <ZH>: Hey, Eventbot put this on staff chat.. why is it in this format? Staff, please start a new game in Baseball or hockey. (Requested by Rondo)
```
Unforeseen bug with event recognition ("Baseball" is recognized as "base")

**Comment by connermcd** [comment]
**Comment by Maverick on 17 May 1983 06:41 UTC**
TODO bugfix:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at twcore.core.command.CommandInterpreter.handleEvent(Unknown Source)
	at twcore.bots.eventbot.eventbot.handleEvent(eventbot.java:103)
	at twcore.core.util.MessageLimiter.handleEvent(Unknown Source)
	at twcore.core.net.GamePacketInterpreter.handleChatMessage(Unknown Source)
	at twcore.core.net.GamePacketInterpreter.translateNormalPacket(Unknown Source)
	at twcore.core.net.GamePacketInterpreter.translateGamePacket(Unknown Source)
	at twcore.core.net.ReliablePacketHandler.handleReliableMessage(Unknown Source)
	at twcore.core.net.GamePacketInterpreter.translateSpecialPacket(Unknown Source)
	at twcore.core.net.GamePacketInterpreter.translateGamePacket(Unknown Source)
	at twcore.core.Session.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:823)
	at twcore.bots.eventbot.eventbot.removeExpiredRequests(eventbot.java:669)
	at twcore.bots.eventbot.eventbot.cmdRequest(eventbot.java:190)
	... 14 more
```

**Comment by connermcd** [comment]
**Modified by milosh on 4 Oct 1934 00:56 UTC**

**Comment by connermcd** [comment]
**Comment by Maverick on 1 Feb 1978 14:27 UTC**
TODO:

Add a notice (PM to requester) when a request expires. We want this bot as user friendly as possible.

**Comment by connermcd** [comment]
**Comment by Maverick on 16 Apr 1965 00:57 UTC**
Bugs and todos fixed.
This ticket can be closed.
